// This snippet file was generated by processing the source file:
// ./messaging-next/service-worker.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_init_in_sw_modular]
import { initializeApp } from "firebase/app";
import { getMessaging } from "firebase/messaging/sw";

// Initialize the Firebase app in the service worker by passing in
// your app's Firebase config object.
// https://firebase.google.com/docs/web/setup#config-object
const firebaseApp = initializeApp({
  projectId: 'platzi-angular-f4dd3',
  appId: '1:589187018489:web:225660cb6df83628277c28',
  storageBucket: 'platzi-angular-f4dd3.appspot.com',
  apiKey: 'AIzaSyA-FhpQ6IArIqFRHPnVFuTwCjk2Qqx8EvI',
  authDomain: 'platzi-angular-f4dd3.firebaseapp.com',
  messagingSenderId: '589187018489',
});

// Retrieve an instance of Firebase Messaging so that it can handle background
// messages.
const messaging = getMessaging(firebaseApp);
// [END messaging_init_in_sw_modular]
